name: Validate

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v6
        with:
          path: |
            ~/.platformio
          key: ${{ runner.os }}-pio
      - run: pip install platformio
      - run: pio run
